// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJKPYH5lZoyx0iM7jowgZq7QzevoxHceA',
    appId: '1:109692840416:web:57f569d18240e4402e2385',
    messagingSenderId: '109692840416',
    projectId: 'chat-app-pankaj',
    authDomain: 'chat-app-pankaj.firebaseapp.com',
    storageBucket: 'chat-app-pankaj.appspot.com',
    measurementId: 'G-5V3FB3ZRKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADfBjQPFkTZi2KvByLsAhMvTu8YvZXpYw',
    appId: '1:109692840416:android:d5fc9823e20cda812e2385',
    messagingSenderId: '109692840416',
    projectId: 'chat-app-pankaj',
    storageBucket: 'chat-app-pankaj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBLTe14ohmA_rHpYlre5Tkcm01-rUvN68',
    appId: '1:109692840416:ios:2b4c642caf4d3e3a2e2385',
    messagingSenderId: '109692840416',
    projectId: 'chat-app-pankaj',
    storageBucket: 'chat-app-pankaj.appspot.com',
    iosClientId: '109692840416-ij4aojlhbbgd6evbkallmvs87j9o16al.apps.googleusercontent.com',
    iosBundleId: 'com.pankajkcodes.flutterchatapp',
  );
}
